import Head from "next/head";
import Layout from "../../components/layout";
import { useRouter } from "next/router";
import ScNavComponent from "../../components/scNavComponent";
import * as constants from "constants";
import FilterComponent from "../../components/filterComponent";
import Product from "../../elements/product";
import style from "./index.module.css";
import { GrFormNext } from "react-icons/gr";
import { FiGrid } from "react-icons/fi";
import ProductGalleryComponent from "../../components/productGalleryComponent";
import { useEffect, useState } from "react";

const sampleProducts = [
  {
    rating: 4,
    name: "Sweat Pants",
    price: "4.00",
    thumbnails: ["/assets/sampleImages/i.png", "/assets/sampleImages/i_2.png"],
  },
  {
    rating: 4,
    name: "Shirt",
    price: "4.00",
    thumbnails: ["/assets/sampleImages/j.png", "/assets/sampleImages/j_2.png"],
  },
  {
    rating: 4,
    name: "Plushsie",
    price: "3.00",
    thumbnails: ["/assets/sampleImages/k.png", "/assets/sampleImages/k_2.png"],
  },
];
const category = [
  { category: "Women", thumbnail: "/assets/categoriesImages/woman.png" },
  { category: "Watches", thumbnail: "/assets/categoriesImages/watch.png" },
  { category: "Accessories", thumbnail: "/assets/categoriesImages/bag.png" },
  { category: "Sneakers", thumbnail: "/assets/categoriesImages/sneaker.jpg" },
];
const getCategoryTiles = () => {
  function getRandomInt(max) {
    return Math.floor(Math.random() * max);
  }
  let value = getRandomInt(2);
  let array = [
    {
      display: "flex",
      flexDirection: "column",
      marginTop: "auto",
      marginBottom: "auto",
      width: "fit-content",
      marginRight: "auto",
      marginLeft: "1em",
      alignItems: "flex-start",
    },
    {
      display: "flex",
      flexDirection: "column",
      marginTop: "auto",
      marginBottom: "auto",
      width: "fit-content",
      marginLeft: "auto",
      alignItems: "flex-end",
      marginRight: "1em",
    },
  ];
  let orientation = array[value];
  return <></>;
};
export default function Item() {
  const router = useRouter();
  const { item } = router.query;
  const [props, setProps] = useState({});
  useEffect(() => {
    try {
      if (typeof item != "undefined") {
        setProps(JSON.parse(item));
        localStorage.setItem("query", item);
      } else {
        setProps(JSON.parse(localStorage.getItem("query")));
      }
    } catch (err) {}
  }, [item]);
  const image = "/assets/constants/img.jpg";
  return (
    <>
      <Head>
        <title>{props.name}-Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section
          className={style.banner}
          style={{ backgroundColor: "rgb(245, 245, 245)" }}
        >
          <div className={"container"}>
            <div
              style={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "space-between",
                marginTop: "1em",
                marginBottom: "1em",
              }}
            >
              <div
                style={{
                  display: "flex",
                  flexDirection: "row",
                  flexWrap: "wrap",
                }}
              >
                <span
                  className={style.link}
                  style={{ fontSize: "14px", marginRight: "0.2em" }}
                >
                  Home
                </span>
                <span
                  style={{
                    fontSize: "14px",
                    marginRight: "0.2em",
                    color: "#696969",
                  }}
                >
                  <GrFormNext />
                </span>
                <span
                  className={style.link}
                  style={{ fontSize: "14px", marginRight: "0.2em" }}
                >
                  test
                </span>
                <span
                  style={{
                    fontSize: "14px",
                    marginRight: "0.2em",
                    color: "#696969",
                  }}
                >
                  <GrFormNext />
                </span>
                <span
                  className={style.link}
                  style={{ fontSize: "14px", marginRight: "0.2em" }}
                >
                  {props.name}
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "row" }}>
                <FiGrid
                  style={{
                    fontSize: "14px",
                    marginRight: "0.2em",
                    marginTop: "auto",
                    marginBottom: "auto",
                  }}
                />
                <span className={style.link}>
                  <GrFormNext
                    style={{
                      fontSize: "14px",
                      marginTop: "auto",
                      marginBottom: "auto",
                    }}
                  />
                </span>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div style={{ display: "flex", flexDirection: "column" }}>
            <ProductGalleryComponent {...props} />
          </div>
        </section>
        <section>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              marginTop: "2em",
              marginBottom: "1em",
            }}
          >
            <span
              style={{
                textAlign: "center",
                fontSize: "1.5rem",
                fontWeight: "300",
              }}
            >
              You may also like
            </span>

            <div className={"container"}>
              <div
                style={{
                  display: "flex",
                  flexDirection: "row",
                  justifyContent: "space-between",
                  flexWrap: "wrap",
                  overflow: "hidden",
                }}
              >
                {sampleProducts.map((product, i) => {
                  return (
                    <Product
                      name={product.name}
                      key={product.name + "_" + i}
                      thumbnails={product.thumbnails}
                      price={product.price}
                    />
                  );
                })}
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}
