import Head from 'next/head'
import Layout from "../../components/layout";
import { useRouter } from 'next/router'
import style from "./index.module.css"
import Product from "../../elements/wishlistProduct";

const sampleProducts=[{
    rating:4,
    name:"Sweat Pants",
    price:"4.00",
    thumbnails:["/assets/sampleImages/i.png","/assets/sampleImages/i_2.png"]
},
    {
        rating:4,
        name:"Shirt",
        price:"4.00",
        thumbnails:["/assets/sampleImages/j.png","/assets/sampleImages/j_2.png"]
    },
    {
        rating:4,
        name:"Plushsie",
        price:"3.00",
        thumbnails:["/assets/sampleImages/k.png","/assets/sampleImages/k_2.png"]
    }]
const category=[
    {   category:"Women",
        thumbnail:"/assets/categoriesImages/woman.png",},
    {   category:"Watches",
        thumbnail:"/assets/categoriesImages/watch.png",},
    {   category:"Accessories",
        thumbnail:"/assets/categoriesImages/bag.png",},
    {   category:"Sneakers",
        thumbnail:"/assets/categoriesImages/sneaker.jpg",},
]
const getCategoryTiles=()=>{
    function getRandomInt(max) {
        return Math.floor(Math.random() * max);
    }
    let value=getRandomInt(2)
    let array=[{display:"flex",flexDirection:"column",marginTop:'auto',marginBottom:'auto',width:"fit-content",marginRight:"auto",marginLeft: "1em", alignItems:"flex-start"},{display:"flex",flexDirection:"column",marginTop:'auto',marginBottom:'auto',width:"fit-content",marginLeft:'auto',alignItems:"flex-end",marginRight: "1em"}]
    let orientation=array[value]
    return(<></>);
}
export default function Wishlist({props}) {
    const router = useRouter()
    const { collection} = router.query
    const image="/assets/constants/img.jpg"
    return (
        <>
            <Head>
                <title>{collection}-Ecommerce</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section className={style.banner}>
                </section>
                <section>
                    <div style={{position:"relative",display:"flex",flexDirection:"column",width:"100%"
                        ,padding:"4em",backgroundImage:`url(${image})`,backgroundSize:"cover"
                    ,backgroundPosition:"center center"}}>
                        <div style={{backgroundColor:"rgba(0,0,0,0.5)",display:'flex',flexDirection:"column",position:"absolute",width:"100%",right:0,left:0,top:0}}>
                            <h2 style={{marginTop:"2.2em",fontSize:"20px",textAlign:"center",color:"white"}}>New Arrival</h2>
                            <span style={{marginBottom:"2.2em",fontSize:"14px",textAlign:"center",color:"white"}}>Online sneaker Store</span>
                        </div>
                    </div>
                </section>
                <section>

                    <div className={"container"}>
                        <div style={{display:"flex",flexDirection:'row',justifyContent:'space-between',flexWrap:'wrap',overflow:'hidden'}}>
                            {sampleProducts.map((product,i)=>{
                                return ( <Product name={product.name} thumbnails={product.thumbnails} price={product.price}/>)
                            })}
                        </div>
                    </div>
                </section>

            </Layout>
        </>
    )
}
